language: android
dist: trusty

env:
  global:
  - ANDROID_API_LEVEL=31
  - ANDROID_BUILD_TOOLS_VERSION=30.0.3

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-31"
  - yes | sdkmanager "build-tools;30.0.3"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_script:
  - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: 
  - sudo apt-get update
  - sudo apt-get install openjdk-11-jdk
  - ./gradlew clean assembleDebug test -Dorg.gradle.java.home=/usr/lib/jvm/java-11-openjdk-amd64/ --info
